version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "443:443"
    depends_on:
      - mongo
      - redis
    env_file:
      - .env
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo
    #container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    #container_name: redisdb
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
    driver: local

  redis-data:
    driver: local
